### ISSUE TITLE
TTL field and DF flag addition

### ISSUE THREAD

**Issue by fdauti** [ValentinBELYN/icmplib#54] opened 2022-06-08 22:45 UTC
Hello and thank you for your development of icmplib. 

I'm using it as part of a tool for diagnostic purposes. I wanted to ask if it is possible to include these two parameters as part of future development. First one is a "df" parameter as a feature, so that if set to True, will enable the Don't Fragment flag in the IP header. Second one is a ttl return value, corresponding to the ttl field value in received packet. Or maybe there is something related to the above but I'm missing them. 

Thanks again and regards.

**Comment by ValentinBELYN** [comment] 2022-07-10 08:39
Hi @fdauti,

Thanks for using icmplib!

Adding the DF flag should be possible. However, not having enough time to devote to icmplib at the moment, you will have to wait a bit.

For the TTL, there have been several requests in the past on this subject but I do not understand the point of retrieving this information (the remote equipment responds with an initial TTL which may vary). Moreover, not having access to the IP header in IPv6, I can only retrieve this information in IPv4.

**Comment by firefrei** [comment] 2023-03-08 07:55
Hi,
I would also be interested in the DF bit for testing respectively verification of fragmentation in the network. 

Cheers,
Matthias

**Comment by aztec102** [comment] 2023-06-15 13:17
Good afternoon
I’ll also say that I would very much like to see in the library possible checks without fragmentation.

**Comment by TonyFlury** [comment] 2023-08-28 14:20
I Opened an almost Duplicate of this for a DF flag - i think an additional option in the ICMPScoket or ICMPRequest would be the right place - would you object if I did a clone/fork and attempted to build a Pull request to add this feature, or would you prefer to keep development entirely in house ?

**Comment by ValentinBELYN** [comment] 2024-04-21 09:49
Closing in favor of #71.

**Closed by ValentinBELYN** 2024-04-21 09:49 UTC
